# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - ECMSAIUB1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up.NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
         #This will change the working directory to the ECMS.Web project folder before running the dotnet build command.
        run: |
          cd ./src/ECMS/ECMS.Web
          dotnet build --configuration Release

      - name: dotnet publish
         #This will change the working directory to the ECMS.Web project folder before running the dotnet publish command. 
        run: | 
          cd ./src/ECMS/ECMS.Web 
          dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ./src/ECMS/ECMS.Web/${{env.DOTNET_ROOT}}/myapp
          if-no-files-found: error

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
          path: ${{github.workspace}}/myapp

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D97A2CC2F5C04AC4A66D085B172F1335 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_54C8FCE788D84D42A6CC413235A0CE20 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6356BA64CA9747B3AB008802E7FC780B }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ECMSAIUB1'
          slot-name: 'Production'
          package: ${{github.workspace}}/myapp